// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/temporary-mail-redesign/Current.tsx": () => import("../components/mockups/temporary-mail-redesign/Current.tsx"),
  "./components/mockups/temporary-mail-redesign/Dashboard.tsx": () => import("../components/mockups/temporary-mail-redesign/Dashboard.tsx"),
  "./components/mockups/temporary-mail-redesign/Landing.tsx": () => import("../components/mockups/temporary-mail-redesign/Landing.tsx")
};
